hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "2b015e37810d20ee1ed8755e6394298add8107f0e53856d23ceef5fedefa01e6"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "ee04f03692358a09502f0e5142f9f3d7f9319613acbee93a1b4d4caa2fa9208c"
metafile = true

[[files]]
file = "mods/accessorify.pw.toml"
hash = "c1f7da0593fa29c30d9c39654947da33e92cf969f093601bf7f7db61cc368cbd"
metafile = true

[[files]]
file = "mods/almanac-lib.pw.toml"
hash = "58bd191c753979081fc79e02acef9d35b6ebe78fe86cf562a232bd9f632a9c26"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "e77a1e4fd27c350d4294b296d4bf897b42519aa15892154a181b93bf33118a78"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "79e922fb95a62fe980b87997291c151fd01a45e2d3e80e98e819de55be32ab95"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "73b919b955773fed0a472cc3772d4acbed8c72e80186dd4052111fe1cc577dcc"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "25d24bd2dead409fc0583cbc6b89c3df21489a1bf4d262486130cf7c7145f731"
metafile = true

[[files]]
file = "mods/c2me.pw.toml"
hash = "83e7d2b486d9e81ebc87113c3c531f1380b03e4cc5a889ec1e007a553c4e48e0"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "3b537859514d778e5b6451fae25f622079b3a270bbcb8e20ade037d35f043971"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "aae93007fab93e4d114d1c9e22c85b4e3305607f003de5c9bddb335e77d1c3bb"
metafile = true

[[files]]
file = "mods/choicetheorems-overhauled-village.pw.toml"
hash = "f0e21888cc48a0fc9edfe701c28b91e0d57e81d6d2384f3e4e3af2ff80d7fec2"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "5bd8950828a148798f3a5541f1a31f863ecb591c9c4c2f9a02f23efd9bf90ec3"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "8f2c72f3e0dac8b62e92970af303ad04ad783b5eec65bed7a80c03d7fce7437f"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "0172961b40e38e546b6655cc4a19574244f203938a78d4c231dc5a08f86d269d"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "252a3fe876ca70a2bae42609e31b19965abcf67c539ba5b5c1308698a99c8272"
metafile = true

[[files]]
file = "mods/custom-player-models.pw.toml"
hash = "2a2fed5fc864ae5b4b321dc4bbc95ab8115c868803db73fed7999e46d1cee8cb"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "618fbfea9689427eecda8f488e0b3f434134895113c02c3d386e44f370697335"
metafile = true

[[files]]
file = "mods/dcintegration.pw.toml"
hash = "b86fb98e00c28872a6a05eb668d5a1c67a4a12b24b77d3455c38de9161279c08"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "c37b53c2a66e5ce53039353659935c4f2b1b29e5f10716b5a6bb30ef62c92038"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "2df7852b971032c65ce83f1a61ed8babd8eef1e2cef36171e7126c42d59bf265"
metafile = true

[[files]]
file = "mods/elytra-physics.pw.toml"
hash = "6e3bd4a4a5578f544fb0bf80cdb32c397fd4968ebccf0ed615285b7d28c379ed"
metafile = true

[[files]]
file = "mods/enchanted-vertical-slabs.pw.toml"
hash = "c4b5f78005fe7931fd7c4d03556343a5199a23af43f752b771f171fd23040cc8"
metafile = true

[[files]]
file = "mods/ender-villages.pw.toml"
hash = "513019df3c5b8684a13dda1752496afca665016f05775a3d61c317d16a10258f"
metafile = true

[[files]]
file = "mods/endercon.pw.toml"
hash = "80a41e9b236e1e5a27f66c607a9a72a070a8350acc9e2103b42390d63de7819a"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "4a19eb42a4e2ae64a2c1311dee8d9d0657ea25d449ee35ee2516f54e29d30591"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "fed6081ba4b3fc23a1bfe8ccdaadf8afdd25c7bbf7ff4777a02ce36da750b376"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "659b9f80edaa114898f436b8efc46b5a72b81eba89d831e9506a6ef40aaf4d12"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "37995c0f2abd249cc36579043316e0e9f45e38b9e6c3b0b8c1cdbaa25c5d6537"
metafile = true

[[files]]
file = "mods/forgematica.pw.toml"
hash = "9e60a85fe39800476d36b92d1565e4e15fb1561ffd5d6c3a63abc7074ddc32ee"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "0ea5600a3b1c6f04cbd6914447c490244c2ca4fa3412bf47632bcce7e19c1e88"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "c8fc45ac5038ffd5124e4b79b5e829f8033f70edd31f065700e1a8a8310a86e1"
metafile = true

[[files]]
file = "mods/from-the-fog.pw.toml"
hash = "a9e6c38e36fef6be60d4cc671118160d5b5ef830f0e7d01baa1b678b5b4466e0"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "2712e6db409cd8fd91eef7c36bcd2bf1d186dffed2c41b859405de7fa98d6c0d"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "8ce1482f0b9a092683ee7edbd5381509915e22b0a7ca546bf46293f8ce14329e"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
hash = "bf68779d23bc35102ce4540b791f58eb83caeb4065683eb75d766596e4727d3d"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "9562afc1476bc027d20e1c128358272a115a828c06f103c1713d65f3b84a6f04"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "75607dff5408c95f2892aa95d66e8c13ad748d20af106af0e965d6668c1a321f"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "6c67f02d9a8cb6539b1fa065b23b30b96a91de273adfda54e91eeb39dfd1937e"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "c99820fe976007d39db47531d2930d70179607ae48566b7c655875d8cbe9c384"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "105dc91fe82a4cc461900f89f1efab847d61184d78bde445e95f8b99b409ff75"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "8046db79e104b618f4cf5d3483884f82099f0c2bb77ee1c2ef21faa581f1dc65"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "9e51f8934b9ae578792e89ca0cc6d5158f4bc5f14fb1de199a5e40d1fab4dff0"
metafile = true

[[files]]
file = "mods/ketkets-furnicraft.pw.toml"
hash = "2481554122dd77d808f619a1afe541fe015ff066909157ff142ef8225e456619"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "c97f1af3ad41c8ba318a0cf2aa64b1da9c551f74be22fff9e2d5122a34faf41f"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "2eee7e963181362354e729c13106723950064729f134cea67d0a313c1c64fae4"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "9a1b14ed9f7c02fa9432016d10da75c2dd727f67b84d805fe3b1184a5cc104fd"
metafile = true

[[files]]
file = "mods/let-me-despawn.pw.toml"
hash = "19ec02275c1380188ac2cea9d6435212e6228c92ad870d771ab86cd636e83db4"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "ec412163a1b43638371783147f891d729c310fabfac1de97df1f47933614ee23"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "ef0013df6119e228fb9d6a65c2b4b24a43d700de1ad96cedad4882c1ca6c01a7"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "f0d87eb0f83bbfa42f7dc2fbe59374a0a80d4cebed252eb2db9585b8463afccd"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "2d3c1d2266e3c900f10a86be8a3cbb332250f01dfa2257a804a82066607158a4"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "485ff87804b1d05a5ea315416de74eef0695e42b5faaee664db3f1286a154ce5"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
hash = "fff5801e95be0ea0e5d8c7497d58cd18441c86c71c1a9d818c31587bf5dd0916"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "220123b2dd257b5deb7b722f5d74d60d7e1ca32ce6c3181a2da1f3a519b48d8f"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "6e9f24d285e91b2e75fe7c1d70801771e8cb5ed3120b9f1e26a234a13a57cc8e"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "adc7924af2290a1c80628f316ae7f57b481b1f6f249d82fb29f11ebfccee90ef"
metafile = true

[[files]]
file = "mods/mafglib.pw.toml"
hash = "5f2f3caf91aeccbd58bb6768eb5ff9c0a6a0347a0ef13f4a5cebee4d4806c21a"
metafile = true

[[files]]
file = "mods/mcpitanlibarch.pw.toml"
hash = "b9a013a89358571fe11d1dbe69547d7632080d35a63ad9df020defcdda59d218"
metafile = true

[[files]]
file = "mods/mns-moogs-nether-structures.pw.toml"
hash = "1262c73d6e6b1d83bca0e5e48d81c92e943915323710ff310fdfce2fde119465"
metafile = true

[[files]]
file = "mods/monolib.pw.toml"
hash = "b8a28b068dbd8127481e8b7928a94604bd9fba5b8b57afaafc017bbc66fdf547"
metafile = true

[[files]]
file = "mods/moogs-end-structures.pw.toml"
hash = "e03b66c806c52193722f066dcbb8918fe44e45fdabe5ea562e8a435f6b0affa3"
metafile = true

[[files]]
file = "mods/moogs-structure-lib.pw.toml"
hash = "b6693ae5640dd4a7542f2bd3713447714e31e3b6526f697fda427b6c36993794"
metafile = true

[[files]]
file = "mods/moogs-voyager-structures.pw.toml"
hash = "1d49d388cd1a4317c1663672b41acbf11cb4c5c2c731b231308a3ed655f555ae"
metafile = true

[[files]]
file = "mods/more-harnesses.pw.toml"
hash = "d47d0590371c79a94851c428edb589be1cf042903ecb4e4a8d4d0521e5cfab55"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "89fef98a57bc5bf17a0896f6ee166489ef0f5d767618973534d9acef102baff8"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "23950f373c3ae696c4c61552e42f2d457870147bcdc6604241c2d44dd403b250"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "714a556237d415b7736a78a12a6da8d401d773573bc7bcc58495f104b7a6728e"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
hash = "ea00e04890e392149b5b710997ee4f1fe9a1e5f062be3cfc5cfc84cb06c22d21"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "1d44f229e6b412fcaf6cad52e91c2d9296d133e17257958e0dd2e5ed1b104f0d"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "22e3e7d7aceda931c46922f4872b3f2d4ad41ba1cb6dfa3949a3df4e06de5ee8"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "ca47ac07ab084bd7f657a7771a264d9ce399ade1c2e678352e03bbf12c8b3281"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "0a6564b720c7b524d08e1f2c4d0b1a3a082bf98c5f3d142678cd5b25c16557ab"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "215039ec9a0d262b04b3950ed16ee3c18d387c82e1b0767a56badbc5ee14f824"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "27d2beab65b090b670b286fc05cc43b07582be21640c8eae0e0e4a0bf598e5d3"
metafile = true

[[files]]
file = "mods/snowy-weaponry.pw.toml"
hash = "5afb22daeacb6fbf6577c7462e2f0bc81c6be90fdccad0d49b8debfbf5508478"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "6d51169189704b9c3c6aa268e998273a63ed94360b95ca4f24c3a08047557693"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "d0a35afaa1e68dd9640db999474896cc927261b2d2ab7d215a209e0e4c7585dc"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "f9786d8da1084fac8e91089e1d98f9a8b16e6bd4ad31989291465142bc7525f2"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "f4da69fe35a46fe382875541aa0d1c4c4b39caba465c638b0e5ead0960be33aa"
metafile = true

[[files]]
file = "mods/sort-it-out.pw.toml"
hash = "cc7e37e044717e60160f28db286c0e69065620ae1967f7733fab4a48334355a7"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "20b6a77277a812cac129f3e7cb4f09f0b64f90db4af8a424b8618601277ad4de"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "6959efdd2e0d1616a4ad041d601a45fcc061942139a4c91747ed8b92583099a8"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
hash = "6289394c0060e1e698b35cfbf5bf5621fa6e455214eab03afe31e21474eb6998"
metafile = true

[[files]]
file = "mods/structory.pw.toml"
hash = "ad278104876f2e043fa466b90be7b71c1ad4f53710e30f3c43a52ab4cbeb24a6"
metafile = true

[[files]]
file = "mods/terrablender-neoforge.pw.toml"
hash = "896ad08d8b2ca69b626b63d2ec9d38ed43b6f8d739a3410208a1b185ef544216"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "9ce82dabe8a4ec3f4bff08a2a76aa4be26d33ed764e6b545f12459bd47b50f62"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "6cb3b398e9e8aa0e3e87fa04a46b6954ab36ddcc8bd916f454073261aae8c0b9"
metafile = true

[[files]]
file = "mods/vivecraft.pw.toml"
hash = "8d4dc4e0e1eb4278b530d4be1b5881962ca2bf518023966923457754541fe2ca"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "b769a2f7ef2fa754224c5068491e79d02c0c85e0bc326fc05247f18315cc866b"
metafile = true
