hash-format = "sha256"

[[files]]
file = "better-mc-fabric-bmc2.pw.toml"
hash = "c60033ecb089384198afb8b9217e15e21c16964aafbc34b13404a875d2a3bc25"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
hash = "c325387d3cbdf2658de2a51ea6235b610505c6de8dc8be71799d050c713c88a2"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "429284603e4c5ca44777cb4ce2455477fcc1eee4dc9a4ae2f759c4895bf332e7"
metafile = true

[[files]]
file = "mods/cynosure.pw.toml"
hash = "9588e8b0289c498aa3fc55d2bdd2483dc703655abf102beb65fce24cbb34e399"
metafile = true

[[files]]
file = "mods/dcintegration-fabric.pw.toml"
hash = "28969cd0687a1c5f81a0003e4aab0eece8d5cb7d962395c6026145b9d569c5ae"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "47fd33da68d0b13cdffd4124f5bc9cff64caa2878ce7e979ba8092400c2ae1eb"
metafile = true

[[files]]
file = "mods/estrogen.pw.toml"
hash = "28c3f62235e6d76c7f220910c97f1a6e3b96c2b1437bc6c667b9e4ebd766a419"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "76c4b5a7d1d354d678ff27afdc45134c357933d57f889f6738ca7a9d24772508"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "f6629a3c5e023a96cb5d78d66e93b47245996c46a079921b3f6a6094209dc1b0"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
hash = "22d00e3ff006602f7bf31e15df82f2e76555ca82ad8111f650bd215ac7f472f9"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "bc91fa90e9f26f3ff3690c1a508647a162cd63dc36d815b8af0d6f5e01e5ecbf"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "3c2fe6485d980a094a5094263d9d54dd59bd4cfd37439109be561894342a82f8"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "3f9e020fb15e1c2ede36d50b40c72d536f6de3f817bd703d26805a747175c8bc"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "ffdb79f5bc29f990e5889f5d159a043c7046b8cd8d79f17f54b44d7ccc2b242a"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "c709708a11f117743c086f16de67701eb35bfad331826960398bb1e64ea4d35f"
metafile = true
