hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "2b015e37810d20ee1ed8755e6394298add8107f0e53856d23ceef5fedefa01e6"
metafile = true

[[files]]
file = "mods/almanac-lib.pw.toml"
hash = "58bd191c753979081fc79e02acef9d35b6ebe78fe86cf562a232bd9f632a9c26"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "25d24bd2dead409fc0583cbc6b89c3df21489a1bf4d262486130cf7c7145f731"
metafile = true

[[files]]
file = "mods/c2me.pw.toml"
hash = "83e7d2b486d9e81ebc87113c3c531f1380b03e4cc5a889ec1e007a553c4e48e0"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "3b537859514d778e5b6451fae25f622079b3a270bbcb8e20ade037d35f043971"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "aae93007fab93e4d114d1c9e22c85b4e3305607f003de5c9bddb335e77d1c3bb"
metafile = true

[[files]]
file = "mods/choicetheorems-overhauled-village.pw.toml"
hash = "f0e21888cc48a0fc9edfe701c28b91e0d57e81d6d2384f3e4e3af2ff80d7fec2"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "68eb6171f75a74abc16999700d18f839100b6bbf88b80f4d143e938883a9b9ce"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "252a3fe876ca70a2bae42609e31b19965abcf67c539ba5b5c1308698a99c8272"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "4a19eb42a4e2ae64a2c1311dee8d9d0657ea25d449ee35ee2516f54e29d30591"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "fed6081ba4b3fc23a1bfe8ccdaadf8afdd25c7bbf7ff4777a02ce36da750b376"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "659b9f80edaa114898f436b8efc46b5a72b81eba89d831e9506a6ef40aaf4d12"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "779e5baff02df5a747a769faa8cd8036fbdbdc52fc19f9a6cb039e4afa8048dd"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "9562afc1476bc027d20e1c128358272a115a828c06f103c1713d65f3b84a6f04"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "75607dff5408c95f2892aa95d66e8c13ad748d20af106af0e965d6668c1a321f"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "54a5e4d994cf7e2520f99a7d7b5b6ef728da3f95238c3dd32568854aeeca6bf2"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "8046db79e104b618f4cf5d3483884f82099f0c2bb77ee1c2ef21faa581f1dc65"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "9e51f8934b9ae578792e89ca0cc6d5158f4bc5f14fb1de199a5e40d1fab4dff0"
metafile = true

[[files]]
file = "mods/ketkets-furnicraft.pw.toml"
hash = "2481554122dd77d808f619a1afe541fe015ff066909157ff142ef8225e456619"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "2eee7e963181362354e729c13106723950064729f134cea67d0a313c1c64fae4"
metafile = true

[[files]]
file = "mods/let-me-despawn.pw.toml"
hash = "19ec02275c1380188ac2cea9d6435212e6228c92ad870d771ab86cd636e83db4"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "ec412163a1b43638371783147f891d729c310fabfac1de97df1f47933614ee23"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "ef0013df6119e228fb9d6a65c2b4b24a43d700de1ad96cedad4882c1ca6c01a7"
metafile = true

[[files]]
file = "mods/mns-moogs-nether-structures.pw.toml"
hash = "1262c73d6e6b1d83bca0e5e48d81c92e943915323710ff310fdfce2fde119465"
metafile = true

[[files]]
file = "mods/monolib.pw.toml"
hash = "b8a28b068dbd8127481e8b7928a94604bd9fba5b8b57afaafc017bbc66fdf547"
metafile = true

[[files]]
file = "mods/moogs-end-structures.pw.toml"
hash = "e03b66c806c52193722f066dcbb8918fe44e45fdabe5ea562e8a435f6b0affa3"
metafile = true

[[files]]
file = "mods/moogs-structure-lib.pw.toml"
hash = "b6693ae5640dd4a7542f2bd3713447714e31e3b6526f697fda427b6c36993794"
metafile = true

[[files]]
file = "mods/moogs-voyager-structures.pw.toml"
hash = "1d49d388cd1a4317c1663672b41acbf11cb4c5c2c731b231308a3ed655f555ae"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "89fef98a57bc5bf17a0896f6ee166489ef0f5d767618973534d9acef102baff8"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "9ba7cfeedd6cde2e6ce25976c99ba478c878adb000c401b7dadf7dcdde7ce936"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "0a6564b720c7b524d08e1f2c4d0b1a3a082bf98c5f3d142678cd5b25c16557ab"
metafile = true

[[files]]
file = "mods/snowy-weaponry.pw.toml"
hash = "5afb22daeacb6fbf6577c7462e2f0bc81c6be90fdccad0d49b8debfbf5508478"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "6d51169189704b9c3c6aa268e998273a63ed94360b95ca4f24c3a08047557693"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "20b6a77277a812cac129f3e7cb4f09f0b64f90db4af8a424b8618601277ad4de"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
hash = "6289394c0060e1e698b35cfbf5bf5621fa6e455214eab03afe31e21474eb6998"
metafile = true

[[files]]
file = "mods/structory.pw.toml"
hash = "ad278104876f2e043fa466b90be7b71c1ad4f53710e30f3c43a52ab4cbeb24a6"
metafile = true

[[files]]
file = "mods/terrablender-neoforge.pw.toml"
hash = "896ad08d8b2ca69b626b63d2ec9d38ed43b6f8d739a3410208a1b185ef544216"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "9ce82dabe8a4ec3f4bff08a2a76aa4be26d33ed764e6b545f12459bd47b50f62"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "b769a2f7ef2fa754224c5068491e79d02c0c85e0bc326fc05247f18315cc866b"
metafile = true
