name = "Mc"
author = "ana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "345d82cdd6e30f3a6110b657bc4526d4d1a375426d488561d059238bf5bf351a"

[versions]
minecraft = "1.21.10"
neoforge = "21.10.52-beta"
