name = "Mc"
author = "ana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ff482a6904f79c7eaeaed3f1c9f7122db8213dfe169fad86f5522b58ce66c10"

[versions]
minecraft = "1.21.10"
neoforge = "21.10.55-beta"
