name = "Mc"
author = "ana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ebfc3b245b8fc389a9f566768035c1c928bfbfc37bb9f401b7089d6da529746"

[versions]
minecraft = "1.21.10"
neoforge = "21.10.55-beta"
