name = "Mc"
author = "ana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "519be5906bcbe58d3b97ec66e677ba35d097301830b46f8af447a6d712e2a38e"

[versions]
minecraft = "1.21.10"
neoforge = "21.10.52-beta"
