name = "Mc"
author = "ana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4aeae176bf3c83b7e49838ac6314fc04e8f7efe2fcbafca67564193348b62dfc"

[versions]
minecraft = "1.21.10"
neoforge = "21.10.52-beta"
