name = "Mc"
author = "ana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0663ddf65cec121d0999c7d28bf283e8a21a55fa213ccc5edac220e676a975a7"

[versions]
minecraft = "1.21.10"
neoforge = "21.10.55-beta"
